export type RuleBullet = { bold: string; body: string }

export type RuleSectionModel = {
  id: string
  title: string
  bullets: RuleBullet[]
}

export const GAME_RULE_SECTIONS: RuleSectionModel[] = [
  {
    id: 'cricket',
    title: 'Cricket Betting Rules',
    bullets: [
      {
        bold: 'Match winner:',
        body: ' Bets are settled on the official result published by the governing body. If D/L or VJD is applied, settlement follows that official outcome.',
      },
      {
        bold: 'Minimum overs:',
        body: ' For limited-overs formats, markets stand only if minimum overs criteria are met under the tournament rules. If criteria are not met, unsettled markets are void and stake is returned.',
      },
      {
        bold: 'Innings and session markets:',
        body: ' Session, fancy, and innings runs are settled on the official score at completion or official stoppage of that segment.',
      },
      {
        bold: 'Postponed or abandoned matches:',
        body: ' If a match is not completed as per official schedule and reserve-day policy, undecided markets are void. Already decided markets remain settled.',
      },
      {
        bold: 'Player markets:',
        body: ' Player performance markets are settled using official stats. If the player does not participate in the relevant market condition, bets may be void as per market type.',
      },
    ],
  },
  {
    id: 'football',
    title: 'Football Betting Rules',
    bullets: [
      {
        bold: 'Normal-time settlement:',
        body: ' 1X2, handicap, and total goals are settled on 90 minutes plus injury time only, unless market states extra time or penalties included.',
      },
      {
        bold: 'Postponement window:',
        body: ' If a fixture is not played within the stated market window (commonly 48 hours unless specified), unsettled bets are void.',
      },
      {
        bold: 'Abandonment:',
        body: ' On abandoned matches, markets already decided are settled and all remaining undecided markets are void.',
      },
      {
        bold: 'Goals and own goals:',
        body: ' Total goals and score-based markets follow official match reports and accredited stats providers.',
      },
      {
        bold: 'Cards and corners:',
        body: ' Settled as per official statistics for normal time play. Events awarded but not taken generally do not count.',
      },
    ],
  },
  {
    id: 'tennis',
    title: 'Tennis & Other Sports',
    bullets: [
      {
        bold: 'Tennis match winner:',
        body: ' Settled on the player who officially progresses or is declared winner by tournament authority.',
      },
      {
        bold: 'Retirement and walkover:',
        body: ' If play has not started and official walkover is declared, bets are void. If retirement happens after start, settlement depends on market type and governing rules.',
      },
      {
        bold: 'Other sports:',
        body: ' All markets are settled from official governing-body results, score feeds, and rule books.',
      },
    ],
  },
  {
    id: 'casino',
    title: 'Casino & Games Rules',
    bullets: [
      {
        bold: 'Teen Patti and card games:',
        body: ' Game outcomes follow the in-table rules shown by provider. Hand ranking and tie logic are taken from the live or RNG game engine.',
      },
      {
        bold: 'Roulette:',
        body: ' Settlement is based on the final wheel pocket result shown by the provider for that round.',
      },
      {
        bold: 'Slots and RNG games:',
        body: ' Results are generated by certified RNG systems. Completed rounds are final unless provider reports a technical malfunction.',
      },
      {
        bold: 'Live casino:',
        body: ' Dealer calls and provider game logs are treated as final reference for settlement.',
      },
      {
        bold: 'Bonuses and promotions:',
        body: ' Offer validity, wagering requirement, game contribution, and expiry are governed by promo terms shown in your account.',
      },
    ],
  },
  {
    id: 'general',
    title: 'General Rules',
    bullets: [
      {
        bold: 'Eligibility:',
        body: ' You must be 18+ and legally allowed to use betting and gaming services in your jurisdiction.',
      },
      {
        bold: 'Single account policy:',
        body: ' One user may hold one active account only. Incorrect KYC details, duplicate accounts, or account sharing may lead to restrictions.',
      },
      {
        bold: 'Odds and limits:',
        body: ' Accepted odds at placement time are final. We may limit stakes, cancel obvious-price-error bets, or apply payout caps as per terms.',
      },
      {
        bold: 'Responsible gaming:',
        body: ' Use available controls like deposit limits, session controls, and self-exclusion whenever needed.',
      },
      {
        bold: 'Terms acceptance:',
        body: ' By betting or playing games on this platform, you agree to the latest Game Rules and Terms and Conditions.',
      },
    ],
  },
  {
    id: 'settlement',
    title: 'Settlement, Void & Fair Play',
    bullets: [
      {
        bold: 'Official source:',
        body: ' All market settlements are based on official results, provider data, and recognized sports statistics feeds.',
      },
      {
        bold: 'Dead heat:',
        body: ' If multiple selections tie for a paid position, dead-heat calculation is applied proportionately to stake and odds.',
      },
      {
        bold: 'Void markets:',
        body: ' Cancelled events, technical errors, duplicated markets, or rule breaches can lead to void settlement with stake refund.',
      },
      {
        bold: 'Disputes and fair play:',
        body: ' For settlement queries, raise a Help / Support ticket with your bet ID and event details. Fraud, bot use, collusion, or abuse may result in account action.',
      },
    ],
  },
]
